/* 커스텀마이징 insert 
 * 해당 이미지 upload 폴더에 넣어놓음 
 * 프렌차이즈 시퀀스 2~9번까지 박아넣었으니 프렌차이즈 생성 후 insert하기
 * 회원 시퀀스 5번으로 박아 넣었으니 회원가입해서 5번까지 생성후 insert 하기 */

Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,9,'5','악마의레시피','그린티 프라푸치노와 간 자바칩, 샷 등을 넣어 만든 커스텀 메뉴로 그린트와 초코의 맛을 느낄 수 있다','그린티프라푸치노와 자바칩을 갈고 그 위에 샷을 붓는다. 위에 휘핑을 올리고 통 자바칩과 초코드리즐을 올린다.','147568783005244.jpg','그린티,자바칩,샷,초코,드리즐',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,2,'5','돼지바 프라프치노','돼지바 아이스크림과 같은 맛을 느낄 수 있다','딸기시럽 2펌프 넣고 자바칩 갈고 휘핑과 초코 드리즐을 추가한다','147568793189244.jpg','딸기시럽,자바칩,휘핑,초코,드리즐',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,2,'5','     트윅스 프라프치노','트윅스 같은 맛을 느낄 수 있다','카라멜프라푸치노에 헤이즐넛시럽 한펌프와 자바칩을 넣고 휘핑과 통자바, 초코드리즐, 카라멜드리즐을 더 추가한다.','147571826567445.jpg','카라멜,헤이즐넛,자바칩,초코,드리즐',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,5,'5','아몬드 크림라떼','아몬드와 크림의 고소함을 느낄 수 있다.','아몬드 우유를 선택하고 리스트레또샷을 선택하고 휩을 추가한다.','147568800549138.jpg','아몬드,리스트레또,샷',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,6,'5','체리쥬빌레','체리쥬빌레 아이스크립과 같은 맛을 느낄 수 있다.','바닐라 블렌디드에 엑스트라 체리를 추가한다','147568804045940.jpg','바닐라,체리',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,7,'5','악마의 음료','그린티 프라푸치노와 간 자바칩, 샷 등을 넣어 만든 커스텀 메뉴로 그린트와 초코의 맛을 느낄 수 있다','그린티프라푸치노와 자바칩을 갈고 그 위에 샷을 붓는다. 위에 휘핑을 올리고 통 자바칩과 초코드리즐을 올린다.','147568820762639.jpg','그린티,자바칩,샷,초코,드리즐',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,2,'5',' 콜드브루1','원두가루를 냉침하여 우려낸 커피로 부드럽다','원두가루를 냉침하여 우려낸 커피로 부드럽다','147568835011134.jpg','카라멜,헤이즐넛,자바칩,초코,드리즐',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,8,'5','아몬드 크림라떼','아몬드와 크림의 고소함을 느낄 수 있다.','아몬드 우유를 선택하고 리스트레또샷을 선택하고 휩을 추가한다.','147568842191045.jpg','아몬드,리스트레또,샷',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,2,'5','악마의 레시피!','그린티 프라푸치노와 간 자바칩, 샷 등을 넣어 만든 커스텀 메뉴로 그린트와 초코의 맛을 느낄 수 있다..','그린티프라푸치노와 자바칩을 갈고 그 위에 샷을 붓는다. 위에 휘핑을 올리고 통 자바칩과 초코드리즐을 올린다...','14757034637350.jpg','그린티,자바칩,샷,초코,드리즐,허쉬',0,sysdate);
Insert into CUSTOMIZING (CUSTOM_NUM,FRANCHISE_NUM,U_UID,CUSTOM_NAME,CUSTOM_INTRODUCE,CUSTOM_RECIPE,CUSTOM_IMG,CUSTOM_HASH_TAG,CUSTOM_VISIT,CUSTOM_REG_DATE) values (customizing_seq.nextval,3,'5','돼지바 프라프치노','돼지바 아이스크림과 같은 맛을 느낄 수 있다','딸기시럽 2펌프 넣고 자바칩 갈고 휘핑과 초코 드리즐을 추가한다','147568858340538.jpg','딸기시럽,자바칩,휘핑,초코,드리즐',0,sysdate);